//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVLaJoya.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devprontipagos.domainscm.com:28181/siveta-endpoint-ws-1.0-SNAPSHOT/Prontip" +
            "agosTopUpServiceEndPoint")]
        public string PVLaJoya_ProntiPagos_ProntipagosTopUpServiceEndPoint {
            get {
                return ((string)(this["PVLaJoya_ProntiPagos_ProntipagosTopUpServiceEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\BD\\PuntoVenta" +
            ".mdf;Integrated Security=True")]
        public string PuntoVentaConnectionString {
            get {
                return ((string)(this["PuntoVentaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\sqlexpress;Persist Security Info=True;User ID=sa;Password=L" +
            "aJoya123")]
        public string ConnLaJoya {
            get {
                return ((string)(this["ConnLaJoya"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.prontipagos.mx:80/siveta-endpoint-ws-1.0-SNAPSHOT/ProntipagosTopUpServi" +
            "ceEndPoint")]
        public string PVLaJoya_mx_prontipagos_ws_ProntipagosTopUpServiceEndPoint {
            get {
                return ((string)(this["PVLaJoya_mx_prontipagos_ws_ProntipagosTopUpServiceEndPoint"]));
            }
        }
    }
}
